name: Generate output files from updated tokens

on:
  # Triggers the workflow on push events to the input folder
  push:
    branches:
      - main
    paths:
      - 'input/**'
  
jobs:
  # Generates output files and commit/push to design-tokens repo
  generate-tokens:
    runs-on: macos-latest
    
    env: 
      TARGET_REPO_NAME: localization
=      CONFIG_GITHUB_EMAIL: vinhgv2206@gmail.com
      CONFIG_GITHUB_USERNAME: vinhgiap

    steps:
      - uses: actions/checkout@v3

      - name: install brew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: install convert csv to strings files.
        run: brew tap rogermolas/csv-localizer
        
      - name: install convert csv to strings files.
        run: brew install csv-localizer
        
      - name: show files.
        run: ls
        
      - name: remove old localizations folder.
        run: rm -rf ./output
        
      - name: show files.
        run: ls

        
      - name: general file strings.
        run: csv-localizer -p ios -i ./input -o  ./
        
      - name: show files.
        run: ls
        
      - name: Config git credentials
        run: |        
          git config --local user.email "$CONFIG_GITHUB_EMAIL"
          git config --local user.name "$CONFIG_GITHUB_USERNAME"
        
      - name: Commit files
        run: |
          git status
          git add .
          git commit -m "Add changes"
             
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.SECRET_GITHUB_TOKEN }}
          branch: main
        
