name: Generate output files from updated tokens

on:
  # Triggers the workflow on push events to the input folder
  push:
    branches:
      - main
    paths:
      - 'input/**'
  
jobs:
  # Generates output files and commit/push to design-tokens repo
  generate-tokens:
    runs-on: macos-latest
    
    env: 
      TARGET_REPO_NAME: localization
      BASE_BRANCH: main

    steps:
      - uses: actions/checkout@v3

      - name: install brew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: install convert csv to strings files.
        run: brew tap rogermolas/csv-localizer
        
      - name: install convert csv to strings files.
        run: brew install csv-localizer
        
      - name: remove old localizations folder.
        run: rm -rf ./$TARGET_REPO_NAME/output/*
        
      - name: general file strings.
        run: csv-localizer -p ios -i ./$TARGET_REPO_NAME/input -o ./$TARGET_REPO_NAME
        
      - name: Commit.
        run: git status
             git add .
             git commit -m "General file locables files".
             
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.SECRET_GITHUB_TOKEN }}
          branch: $BASE_BRANCH
        
